// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/check": {
            "get": {
                "description": "basic healthcheck",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "healthcheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/currencies": {
            "get": {
                "description": "Returns list of all currencies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currencies"
                ],
                "summary": "GetAllCurrencies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/exchange-rate": {
            "post": {
                "description": "Inserts new exchange rate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchange-rate"
                ],
                "summary": "InsertExchangeRate",
                "parameters": [
                    {
                        "description": "New exchange rate to insert. Date has to be in RFC3339 format due to gin limitation. Time part will be ignored",
                        "name": "newExchangeRate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExchangeRate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.ExchangeRate"
                        }
                    }
                }
            }
        },
        "/exchange-rate/all-from-date/{date}": {
            "get": {
                "description": "Returns all exchange rates for the given date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchange-rate"
                ],
                "summary": "GetAllExchangeRatesFromDate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date for which exchange rates should be retrived. Date must be formated in YYYY-MM-DD",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "203": {
                        "description": "Non-Authoritative Information",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ExchangeRate"
                            }
                        }
                    }
                }
            }
        },
        "/exchange-rate/last": {
            "get": {
                "description": "Returns most recent exchange rate  which is not null in database for source - destinaion currencies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchange-rate"
                ],
                "summary": "GetLastExchangeRate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "destination currency, default is USD",
                        "name": "destination",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "source, currency",
                        "name": "source",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ExchangeRate"
                        }
                    },
                    "404": {
                        "description": ""
                    }
                }
            }
        },
        "/exchange-rate/range": {
            "get": {
                "description": "Returns exchange rates for currencies in the time period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchange-rate"
                ],
                "summary": "GetRangeExchangeRate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "destination currency, default is USD",
                        "name": "destination",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "source currency",
                        "name": "source",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From date, inclusive, must be formated in YYYY-MM-DD",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Till date, exclusive, must be formated in YYYY-MM-DD",
                        "name": "till",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ExchangeRate"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ExchangeRate": {
            "type": "object",
            "required": [
                "date",
                "destination",
                "source"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2022-05-01T00:00:00.00Z"
                },
                "destination": {
                    "type": "string",
                    "example": "CHF"
                },
                "rate": {
                    "type": "number",
                    "example": 1.0456
                },
                "source": {
                    "type": "string",
                    "example": "USD"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Rate Exchange API",
	Description:      "Provides basic functionality for checking currency exchange rate.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
