basePath: /
definitions:
  models.ExchangeRate:
    properties:
      date:
        type: string
      destination:
        type: string
      rate:
        type: number
      source:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: Provides basic functionality for checking currency exchange rate.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Rate Exchange API
  version: "1.0"
paths:
  /check:
    get:
      description: basic healthcheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: healthcheck
      tags:
      - healthcheck
  /currencies:
    get:
      consumes:
      - application/json
      description: Returns list of all currencies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: GetAllCurrencies
      tags:
      - currencies
  /exchange-rate:
    post:
      consumes:
      - application/json
      description: Inserts new exchange rate
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: InsertSingleExchangeRate
      tags:
      - exchange-rate
  /exchange-rate/all-from-date/{date}:
    get:
      consumes:
      - application/json
      description: Returns all exchange rates for the given date
      parameters:
      - description: Date for which exchange rates should be retrived
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: GetAllExchangeRatesFromDate
      tags:
      - exchange-rate
  /exchange-rate/last:
    get:
      consumes:
      - application/json
      description: Returns most recent exchange rate source - destinaion currencies
      parameters:
      - description: source currency, default is USD
        in: query
        name: source
        type: string
      - description: destination, currency
        in: query
        name: destination
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ExchangeRate'
        "404":
          description: ""
      summary: GetLastExchangeRate
      tags:
      - exchange-rate
  /exchange-rate/range:
    get:
      consumes:
      - application/json
      description: Returns exchange rates for currencies in the time period
      parameters:
      - description: source currency, default is USD
        in: query
        name: source
        required: true
        type: string
      - description: destination currency
        in: query
        name: destination
        type: string
      - description: From date, inclusive
        in: query
        name: from
        required: true
        type: string
      - description: Till date, exclusive
        in: query
        name: till
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: GetrangeExchangeRate
      tags:
      - exchange-rate
schemes:
- http
swagger: "2.0"
