version: '3'

services:
  exchangeRateApi:
    image: kolan1992/exchange_rate_api
    restart: on-failure
    depends_on:
      - postgresql
    environment:
        - DB_USER=root
        - DB_PASSWORD=password
        - DB_NAME=root
        - DB_HOST=postgresql
        - DB_PORT=5432
    ports:
       - 8081:8081
  postgresql:
    image: postgres:14.2-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
    ports:
       - 5432:5432

